name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        preCommands: |
          wrangler kv:namespace create KV_AUDIT_LOGS
          apt-get update && apt-get install -y jq
          export KV_NAMESPACE_ID=$(wrangler kv:namespace list | jq -c 'map(select(.title | contains("KV_AUDIT_LOGS")))' | jq -r ".[0].id")
          echo "[env.prod]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV_AUDIT_LOGS\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
        secrets: |
          SECRET_CLOUDFLARE_API_TOKEN
          SECRET_SLACK_WEBHOOK_URL
          CF_ACCOUNT_ID
        environment: prod
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        SECRET_SLACK_WEBHOOK_URL: ${{secrets.SECRET_SLACK_WEBHOOK_URL}}
        SECRET_CLOUDFLARE_API_TOKEN: ${{secrets.SECRET_CLOUDFLARE_API_TOKEN}}
